name: "KiCad CI/CD to render boards"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths:
      # - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/run-kibot.yml'

jobs:
  render:
    strategy:
      fail-fast: false
      matrix:
        board: [ 
          30keys/Asfoora/Asfoora,
          30keys/Batreeq/V1/Batreeq,
          30keys/Batreeq/V2/BatreeqV2,
          30keys/battoota/battoota,
          30keys/battoota_min/battoota_min,
          30keys/wizza/wizza,
          30keys/Wizza-chocV1-MX_Spacing/wizza,
          30keys/wizza-chocV2/wizza,
          30keys/wizza-mx/wizza,
          32keys/battoota-3thumb/battoota,
          32keys/konafa/konafa,
          32keys/konafa_min/konafa_min,
          34keys/basbousa/basbousa,
          36keys/basbousa36/basbousa
          ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        # Required - kibot config file
        config: main.kibot.yaml
        # optional - prefix to output defined in config
        dir: gallery/${{ matrix.board }}/
        # optional - schematic file
        # schema: 'main.kicad_sch'
        # optional - PCB design file
        board: "boards/${{ matrix.board }}.kicad_pcb"
    - uses: actions/upload-artifact@main
      with:
        path: gallery/

  publish: 
    needs: render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: gallery/
      - run: rm -rf pcb_images/*
      - run: mv gallery/artifact/* pcb_images/
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Update gallery (automated)"
          commit_user_name: GitHub Actions Bot
