name: "KiCad CI/CD for Swipe Light main board"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths:
      # - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/run-kibot.yml'

jobs:
  render:
    strategy:
      fail-fast: false
      matrix:
        board: [ 
          boards/30keys/Asfoora/Asfoora.kicad_pcb,
          boards/30keys/Batreeq/Batreeq-plate-top.kicad_pcb,
          boards/30keys/battoota/battoota.kicad_pcb,
          boards/30keys/battoota_min/battoota_min.kicad_pcb,
          boards/30keys/wizza/wizza.kicad_pcb,
          boards/30keys/Wizza-chocV1-MX_Spacing/wizza.kicad_pcb,
          boards/30keys/wizza-chocV2/wizza.kicad_pcb,
          boards/30keys/wizza-mx/wizza.kicad_pcb,
          boards/32keys/battoota-3thumb/battoota.kicad_pcb,
          boards/32keys/konafa/konafa.kicad_pcb,
          boards/32keys/konafa_min/konafa_min.kicad_pcb,
          boards/34keys/basbousa/basbousa.kicad_pcb,
          boards/36keys/basbousa36/basbousa.kicad_pcb
          ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ls -lisah boards/32keys/
    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        # Required - kibot config file
        config: main.kibot.yaml
        # optional - prefix to output defined in config
        dir: gallery/
        # optional - schematic file
        # schema: 'main.kicad_sch'
        # optional - PCB design file
        board: ${{ matrix.board }}
  archive: 
    needs: render
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: gallery

